name: helm-upgrade
run-name: ${{github.actor}} - ${{github.sha}}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Version of the image to deploy'
        type: string
      helm-values-path:
        description: 'Path to the helm values file'
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        description: 'Name of the helm release'
        type: string
        default: 'todoapp'

jobs:  
  deploy-helm:
   runs-on: ubuntu-latest
   environment: ${{ inputs.environment }}
   name: ${{ inputs.helm-release-name }}


   steps:
   - uses: actions/download-artifact@v4
     with:
       name: helm-package
       path: .

   - name: Set up Helm
     uses: azure/setup-helm@v4.2.0
    
   - name: Set up Kubectl
     uses: azure/setup-kubectl@v4
  
   - uses: azure/login@v2
     with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

   - uses: azure/aks-set-context@v3
     with:
      cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}
      resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}

   - name: Deploy Helm to Development
     run: |
        helm upgrade --install --atomic --wait --timeout 3600s --debug todoapp ./todoapp-*.tgz \
        -f ${{ inputs.helm-values-path }} \
        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set secrets.DB_NAME="${{ secrets.DB_NAME }}" \
        --set secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
        --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
        --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
        --set todoapp.image.version="${{ inputs.helm-release-name }}"
        --set global.environment="${{inputs.environment}}"


   

    