name: helm-upgrade
run-name: ${{github.actor}} - ${{github.sha}}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
      version:
        required: true
        description: 'Version of the image to deploy'
        type: string
      helm-values-path:
        description: 'Path to the helm values file'
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        description: 'Name of the helm release'
        type: string
        default: 'todoapp'

jobs:  
  deploy-helm:
   runs-on: ubuntu-latest
   environment: ${{ inputs.environment }}
   name: ${{ inputs.helm-release-name }}


   steps:
   - uses: actions/download-artifact@v4
     with:
       name: helm-package
       path: .

   - uses: actions/download-artifact@v4
     with:
       name: helm-artifacts
       path: .
  
   - uses: actions/download-artifact@v4
     with:
       name: cluster-config
       path: .

   - name: Set up Helm
     uses: azure/setup-helm@v4.2.0
    
   - name: Set up Kubectl
     uses: azure/setup-kubectl@v4
    
   - name: Create cluster
     uses: helm/kind-action@v1
     with:
        config: ./cluster.yml

   - name: Dry run Helm
     run: |
      helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp-*.tgz  \
      -f ${{ inputs.helm-values-path }} \
      --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
      --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
      --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
      --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
      --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
      --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
      --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
      --set todoapp.image.tag="${{ inputs.version }}"
  
   - name: Deploy Helm Chart
     run: |
        helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name}} ./todoapp-*.tgz \
        -f ${{ inputs.helm-values-path }} \
        --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
        --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
        --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
        --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
        --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
        --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
        --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
        --set todoapp.image.version="${{ inputs.version }}" \
        --set global.environment="${{inputs.environment}}"


   

    